name: Generate Images
on:
  workflow_dispatch:

jobs:
  generate-images:
    name: Generate Images
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_METRIC_PAT: ${{ secrets.GH_METRIC_PAT }}
      WAKATIME_URL: ${{ secrets.WAKATIME_URL }}
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
        working-directory: "./generator"
      - run: bun run build
        working-directory: "./generator"
      - run: bun run generate --output ../../../
        working-directory: "./generator"
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: regenerate images"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          branch: "main"
